### ISSUE TITLE
Version of NSIS ? 

### ISSUE THREAD

**Issue by CouinCouin** [nagyrobi/Jingle_Palette#3]
Hi, 

With some chance, do you remember the NSIS version used to make the installer ? 

I added some features to the original source code, like 1) Autofill the palette name when wanted to save a modified one, 2) Display customization, 3) Fixed "bug" where saving a existing palette with a removed jingle won't really remove the jingle on saved palette, 4) Added possibilty to set playback method (Autorepeat/TouchPlay) for each jingle, with of course, 5) Automigration (add color (for the day where I found how to colorize buttons) and playmode params for each jingles) of palette.ini , and I would recreate the installer.

I saw you made yours with NSIS so I downloaded it, but I have errors with . I though it was because I downloaded a too recent version but tried with an older, I still have errors. Of course, I tried on a XP machine :) 

Perhaps it could work with a specific version ? 

If you remember :) 

Thanks !

**Comment by CouinCouin** [comment]
Yop ! 

After some hours of research and testings, I finally succeed to recreate the installer. 
I used NSIS 2.0 and AccessControl plugin, and with some tricks on jp.nsi file, and looks working fine on a french and english XP.  :) 

did you use NSIS 2.0 too ?

**Comment by nagyrobi** [comment]
I don't remember.

If you're re-creating the whole setup, I suggest as a quick fix, to avoid installing it to the default `C:\Program Files` directory as it was in XP times. That directory is read-only to the normal users from Windows Vista and up, and if you install it there, you won't be able to save palettes - as it stores the ini file in the same directory. Jingle Palette works fine if installed to any different read-write directory.

The correct fix would be of course to create a separate `Jingle Palette` directory under `%APPDATA%` and store the ini files there instead of `Program Files`. You need to modify that both in VB and Nsis.

**Comment by CouinCouin** [comment]
Hi, 
Thanks for the tip :) 
I didn't experienced this problem on Win 10 but perhaps it's because I'm the fiirst and only one user of it .
Also, The Audio_Sample folder should be in %APPDATA% too ?

**Comment by ajmorenor** [comment]
Gentlemen
good day
Can somebody help me. When trying to run the source code in Visual Basic 6.0, it requests a license, how did you solve that problem?
Thanks

**Comment by CouinCouin** [comment]
Hi, 

You should buy a licence here https://secure.ingenuware.com/

**Comment by ajmorenor** [comment]
Thanks
